package com.blackoutburst.fallingsquare.graphics;

import android.content.Context;
import android.opengl.GLSurfaceView;
import android.util.AttributeSet;

public class TextureLoader extends GLSurfaceView {

    public static Texture begin;
    public static Texture d0;
    public static Texture d1;
    public static Texture d2;
    public static Texture d3;
    public static Texture d4;
    public static Texture d5;
    public static Texture d6;
    public static Texture d7;
    public static Texture d8;
    public static Texture d9;
    public static Texture da;
    public static Texture end;
    public static Texture particles;
    public static Texture player;
    public static Texture coin;
    public static Texture coin0;
    public static Texture sound0;
    public static Texture sound1;
    public static Texture pause;
    public static Texture play;
    public static Texture exit;
    public static Texture restart;
    public static Texture arrow;
    public static Texture l1;
    public static Texture l2;
    public static Texture l3;
    public static Texture l4;
    public static Texture l5;
    public static Texture l6;
    public static Texture l7;
    public static Texture l8;
    public static Texture l9;
    public static Texture l10;
    public static Texture l11;
    public static Texture l12;
    public static Texture l13;
    public static Texture l14;
    public static Texture l15;
    public static Texture l16;
    public static Texture l17;
    public static Texture l18;
    public static Texture l19;
    public static Texture l20;
    public static Texture l21;
    public static Texture l22;
    public static Texture l23;
    public static Texture l24;
    public static Texture l25;
    public static Texture l26;
    public static Texture l27;
    public static Texture l28;
    public static Texture l29;
    public static Texture l30;
    public static Texture l31;
    public static Texture l32;
    public static Texture l33;
    public static Texture l34;
    public static Texture l35;
    public static Texture l36;
    public static Texture l37;
    public static Texture l38;
    public static Texture l39;
    public static Texture l40;
    public static Texture l41;
    public static Texture l42;
    public static Texture l43;
    public static Texture l44;
    public static Texture l45;
    public static Texture l46;
    public static Texture l47;
    public static Texture l48;
    public static Texture l49;
    public static Texture l50;
    public static Texture l51;
    public static Texture l52;
    public static Texture l53;
    public static Texture l54;
    public static Texture l55;
    public static Texture l56;
    public static Texture l57;
    public static Texture l58;
    public static Texture l59;
    public static Texture l60;
    public static Texture l61;
    public static Texture l62;
    public static Texture l63;
    public static Texture l64;
    public static Texture l65;
    public static Texture l66;
    public static Texture l67;
    public static Texture l68;
    public static Texture l69;
    public static Texture l70;
    public static Texture l71;
    public static Texture l72;
    public static Texture l73;
    public static Texture l74;
    public static Texture l75;
    public static Texture l76;
    public static Texture l77;
    public static Texture l78;
    public static Texture l79;
    public static Texture l80;
    public static Texture l81;
    public static Texture l82;
    public static Texture l83;
    public static Texture l84;
    public static Texture l85;
    public static Texture l86;
    public static Texture l87;
    public static Texture l88;
    public static Texture l89;
    public static Texture l90;
    public static Texture l91;
    public static Texture l92;
    public static Texture l93;
    public static Texture l94;
    public static Texture l95;
    public static Texture l96;
    public static Texture l97;
    public static Texture l98;
    public static Texture l99;
    public static Texture l100;
    public static Texture locked;
    public static Texture p1;
    public static Texture p2;
    public static Texture p3;
    public static Texture p4;
    public static Texture p5;
    public static Texture p6;
    public static Texture p7;
    public static Texture p8;
    public static Texture p9;
    public static Texture p10;

    public TextureLoader(Context context, AttributeSet attrs) {
        super(context, attrs);
        begin = new Texture(getResources().getIdentifier("begin", "drawable", context.getPackageName()));
        d0 = new Texture(getResources().getIdentifier("d0", "drawable", context.getPackageName()));
        d1 = new Texture(getResources().getIdentifier("d1", "drawable", context.getPackageName()));
        d2 = new Texture(getResources().getIdentifier("d2", "drawable", context.getPackageName()));
        d3 = new Texture(getResources().getIdentifier("d3", "drawable", context.getPackageName()));
        d4 = new Texture(getResources().getIdentifier("d4", "drawable", context.getPackageName()));
        d5 = new Texture(getResources().getIdentifier("d5", "drawable", context.getPackageName()));
        d6 = new Texture(getResources().getIdentifier("d6", "drawable", context.getPackageName()));
        d7 = new Texture(getResources().getIdentifier("d7", "drawable", context.getPackageName()));
        d8 = new Texture(getResources().getIdentifier("d8", "drawable", context.getPackageName()));
        d9 = new Texture(getResources().getIdentifier("d9", "drawable", context.getPackageName()));
        da = new Texture(getResources().getIdentifier("da", "drawable", context.getPackageName()));
        end = new Texture(getResources().getIdentifier("end", "drawable", context.getPackageName()));
        particles = new Texture(getResources().getIdentifier("particles", "drawable", context.getPackageName()));
        player = new Texture(getResources().getIdentifier("player", "drawable", context.getPackageName()));
        coin = new Texture(getResources().getIdentifier("coin", "drawable", context.getPackageName()));
        coin0 = new Texture(getResources().getIdentifier("coin0", "drawable", context.getPackageName()));
        sound0 = new Texture(getResources().getIdentifier("sound0", "drawable", context.getPackageName()));
        sound1 = new Texture(getResources().getIdentifier("sound1", "drawable", context.getPackageName()));
        pause = new Texture(getResources().getIdentifier("pause", "drawable", context.getPackageName()));
        play = new Texture(getResources().getIdentifier("play", "drawable", context.getPackageName()));
        exit = new Texture(getResources().getIdentifier("exit", "drawable", context.getPackageName()));
        restart = new Texture(getResources().getIdentifier("restart", "drawable", context.getPackageName()));
        arrow = new Texture(getResources().getIdentifier("arrow", "drawable", context.getPackageName()));
        l1 = new Texture(getResources().getIdentifier("l1", "drawable", context.getPackageName()));
        l2 = new Texture(getResources().getIdentifier("l2", "drawable", context.getPackageName()));
        l3 = new Texture(getResources().getIdentifier("l3", "drawable", context.getPackageName()));
        l4 = new Texture(getResources().getIdentifier("l4", "drawable", context.getPackageName()));
        l5 = new Texture(getResources().getIdentifier("l5", "drawable", context.getPackageName()));
        l6 = new Texture(getResources().getIdentifier("l6", "drawable", context.getPackageName()));
        l7 = new Texture(getResources().getIdentifier("l7", "drawable", context.getPackageName()));
        l8 = new Texture(getResources().getIdentifier("l8", "drawable", context.getPackageName()));
        l9 = new Texture(getResources().getIdentifier("l9", "drawable", context.getPackageName()));
        l10 = new Texture(getResources().getIdentifier("l10", "drawable", context.getPackageName()));
        l11 = new Texture(getResources().getIdentifier("l11", "drawable", context.getPackageName()));
        l12 = new Texture(getResources().getIdentifier("l12", "drawable", context.getPackageName()));
        l13 = new Texture(getResources().getIdentifier("l13", "drawable", context.getPackageName()));
        l14 = new Texture(getResources().getIdentifier("l14", "drawable", context.getPackageName()));
        l15 = new Texture(getResources().getIdentifier("l15", "drawable", context.getPackageName()));
        l16 = new Texture(getResources().getIdentifier("l16", "drawable", context.getPackageName()));
        l17 = new Texture(getResources().getIdentifier("l17", "drawable", context.getPackageName()));
        l18 = new Texture(getResources().getIdentifier("l18", "drawable", context.getPackageName()));
        l19 = new Texture(getResources().getIdentifier("l19", "drawable", context.getPackageName()));
        l20 = new Texture(getResources().getIdentifier("l20", "drawable", context.getPackageName()));
        l21 = new Texture(getResources().getIdentifier("l21", "drawable", context.getPackageName()));
        l22 = new Texture(getResources().getIdentifier("l22", "drawable", context.getPackageName()));
        l23 = new Texture(getResources().getIdentifier("l23", "drawable", context.getPackageName()));
        l24 = new Texture(getResources().getIdentifier("l24", "drawable", context.getPackageName()));
        l25 = new Texture(getResources().getIdentifier("l25", "drawable", context.getPackageName()));
        l26 = new Texture(getResources().getIdentifier("l26", "drawable", context.getPackageName()));
        l27 = new Texture(getResources().getIdentifier("l27", "drawable", context.getPackageName()));
        l28 = new Texture(getResources().getIdentifier("l28", "drawable", context.getPackageName()));
        l29 = new Texture(getResources().getIdentifier("l29", "drawable", context.getPackageName()));
        l30 = new Texture(getResources().getIdentifier("l30", "drawable", context.getPackageName()));
        l31 = new Texture(getResources().getIdentifier("l31", "drawable", context.getPackageName()));
        l32 = new Texture(getResources().getIdentifier("l32", "drawable", context.getPackageName()));
        l33 = new Texture(getResources().getIdentifier("l33", "drawable", context.getPackageName()));
        l34 = new Texture(getResources().getIdentifier("l34", "drawable", context.getPackageName()));
        l35 = new Texture(getResources().getIdentifier("l35", "drawable", context.getPackageName()));
        l36 = new Texture(getResources().getIdentifier("l36", "drawable", context.getPackageName()));
        l37 = new Texture(getResources().getIdentifier("l37", "drawable", context.getPackageName()));
        l38 = new Texture(getResources().getIdentifier("l38", "drawable", context.getPackageName()));
        l39 = new Texture(getResources().getIdentifier("l39", "drawable", context.getPackageName()));
        l40 = new Texture(getResources().getIdentifier("l40", "drawable", context.getPackageName()));
        l41 = new Texture(getResources().getIdentifier("l41", "drawable", context.getPackageName()));
        l42 = new Texture(getResources().getIdentifier("l42", "drawable", context.getPackageName()));
        l43 = new Texture(getResources().getIdentifier("l43", "drawable", context.getPackageName()));
        l44 = new Texture(getResources().getIdentifier("l44", "drawable", context.getPackageName()));
        l45 = new Texture(getResources().getIdentifier("l45", "drawable", context.getPackageName()));
        l46 = new Texture(getResources().getIdentifier("l46", "drawable", context.getPackageName()));
        l47 = new Texture(getResources().getIdentifier("l47", "drawable", context.getPackageName()));
        l48 = new Texture(getResources().getIdentifier("l48", "drawable", context.getPackageName()));
        l49 = new Texture(getResources().getIdentifier("l49", "drawable", context.getPackageName()));
        l50 = new Texture(getResources().getIdentifier("l50", "drawable", context.getPackageName()));
        l51 = new Texture(getResources().getIdentifier("l51", "drawable", context.getPackageName()));
        l52 = new Texture(getResources().getIdentifier("l52", "drawable", context.getPackageName()));
        l53 = new Texture(getResources().getIdentifier("l53", "drawable", context.getPackageName()));
        l54 = new Texture(getResources().getIdentifier("l54", "drawable", context.getPackageName()));
        l55 = new Texture(getResources().getIdentifier("l55", "drawable", context.getPackageName()));
        l56 = new Texture(getResources().getIdentifier("l56", "drawable", context.getPackageName()));
        l57 = new Texture(getResources().getIdentifier("l57", "drawable", context.getPackageName()));
        l58 = new Texture(getResources().getIdentifier("l58", "drawable", context.getPackageName()));
        l59 = new Texture(getResources().getIdentifier("l59", "drawable", context.getPackageName()));
        l60 = new Texture(getResources().getIdentifier("l60", "drawable", context.getPackageName()));
        l61 = new Texture(getResources().getIdentifier("l61", "drawable", context.getPackageName()));
        l62 = new Texture(getResources().getIdentifier("l62", "drawable", context.getPackageName()));
        l63 = new Texture(getResources().getIdentifier("l63", "drawable", context.getPackageName()));
        l64 = new Texture(getResources().getIdentifier("l64", "drawable", context.getPackageName()));
        l65 = new Texture(getResources().getIdentifier("l65", "drawable", context.getPackageName()));
        l66 = new Texture(getResources().getIdentifier("l66", "drawable", context.getPackageName()));
        l67 = new Texture(getResources().getIdentifier("l67", "drawable", context.getPackageName()));
        l68 = new Texture(getResources().getIdentifier("l68", "drawable", context.getPackageName()));
        l69 = new Texture(getResources().getIdentifier("l69", "drawable", context.getPackageName()));
        l70 = new Texture(getResources().getIdentifier("l70", "drawable", context.getPackageName()));
        l71 = new Texture(getResources().getIdentifier("l71", "drawable", context.getPackageName()));
        l72 = new Texture(getResources().getIdentifier("l72", "drawable", context.getPackageName()));
        l73 = new Texture(getResources().getIdentifier("l73", "drawable", context.getPackageName()));
        l74 = new Texture(getResources().getIdentifier("l74", "drawable", context.getPackageName()));
        l75 = new Texture(getResources().getIdentifier("l75", "drawable", context.getPackageName()));
        l76 = new Texture(getResources().getIdentifier("l76", "drawable", context.getPackageName()));
        l77 = new Texture(getResources().getIdentifier("l77", "drawable", context.getPackageName()));
        l78 = new Texture(getResources().getIdentifier("l78", "drawable", context.getPackageName()));
        l79 = new Texture(getResources().getIdentifier("l79", "drawable", context.getPackageName()));
        l80 = new Texture(getResources().getIdentifier("l80", "drawable", context.getPackageName()));
        l81 = new Texture(getResources().getIdentifier("l81", "drawable", context.getPackageName()));
        l82 = new Texture(getResources().getIdentifier("l82", "drawable", context.getPackageName()));
        l83 = new Texture(getResources().getIdentifier("l83", "drawable", context.getPackageName()));
        l84 = new Texture(getResources().getIdentifier("l84", "drawable", context.getPackageName()));
        l85 = new Texture(getResources().getIdentifier("l85", "drawable", context.getPackageName()));
        l86 = new Texture(getResources().getIdentifier("l86", "drawable", context.getPackageName()));
        l87 = new Texture(getResources().getIdentifier("l87", "drawable", context.getPackageName()));
        l88 = new Texture(getResources().getIdentifier("l88", "drawable", context.getPackageName()));
        l89 = new Texture(getResources().getIdentifier("l89", "drawable", context.getPackageName()));
        l90 = new Texture(getResources().getIdentifier("l90", "drawable", context.getPackageName()));
        l91 = new Texture(getResources().getIdentifier("l91", "drawable", context.getPackageName()));
        l92 = new Texture(getResources().getIdentifier("l92", "drawable", context.getPackageName()));
        l93 = new Texture(getResources().getIdentifier("l93", "drawable", context.getPackageName()));
        l94 = new Texture(getResources().getIdentifier("l94", "drawable", context.getPackageName()));
        l95 = new Texture(getResources().getIdentifier("l95", "drawable", context.getPackageName()));
        l96 = new Texture(getResources().getIdentifier("l96", "drawable", context.getPackageName()));
        l97 = new Texture(getResources().getIdentifier("l97", "drawable", context.getPackageName()));
        l98 = new Texture(getResources().getIdentifier("l98", "drawable", context.getPackageName()));
        l99 = new Texture(getResources().getIdentifier("l99", "drawable", context.getPackageName()));
        l100 = new Texture(getResources().getIdentifier("l100", "drawable", context.getPackageName()));
        locked = new Texture(getResources().getIdentifier("locked", "drawable", context.getPackageName()));
        p1 = new Texture(getResources().getIdentifier("p1", "drawable", context.getPackageName()));
        p2 = new Texture(getResources().getIdentifier("p2", "drawable", context.getPackageName()));
        p3 = new Texture(getResources().getIdentifier("p3", "drawable", context.getPackageName()));
        p4 = new Texture(getResources().getIdentifier("p4", "drawable", context.getPackageName()));
        p5 = new Texture(getResources().getIdentifier("p5", "drawable", context.getPackageName()));
        p6 = new Texture(getResources().getIdentifier("p6", "drawable", context.getPackageName()));
        p7 = new Texture(getResources().getIdentifier("p7", "drawable", context.getPackageName()));
        p8 = new Texture(getResources().getIdentifier("p8", "drawable", context.getPackageName()));
        p9 = new Texture(getResources().getIdentifier("p9", "drawable", context.getPackageName()));
        p10 = new Texture(getResources().getIdentifier("p10", "drawable", context.getPackageName()));
    }

    public static void load(TextureLoader textureLoader, Context context) {
        textureLoader.begin.load(context);
        textureLoader.d0.load(context);
        textureLoader.d1.load(context);
        textureLoader.d2.load(context);
        textureLoader.d3.load(context);
        textureLoader.d4.load(context);
        textureLoader.d5.load(context);
        textureLoader.d6.load(context);
        textureLoader.d7.load(context);
        textureLoader.d8.load(context);
        textureLoader.d9.load(context);
        textureLoader.da.load(context);
        textureLoader.end.load(context);
        textureLoader.particles.load(context);
        textureLoader.player.load(context);
        textureLoader.coin.load(context);
        textureLoader.coin0.load(context);
        textureLoader.sound0.load(context);
        textureLoader.sound1.load(context);
        textureLoader.pause.load(context);
        textureLoader.play.load(context);
        textureLoader.exit.load(context);
        textureLoader.restart.load(context);
        textureLoader.arrow.load(context);
        textureLoader.l1.load(context);
        textureLoader.l2.load(context);
        textureLoader.l3.load(context);
        textureLoader.l4.load(context);
        textureLoader.l5.load(context);
        textureLoader.l6.load(context);
        textureLoader.l7.load(context);
        textureLoader.l8.load(context);
        textureLoader.l9.load(context);
        textureLoader.l10.load(context);
        textureLoader.l11.load(context);
        textureLoader.l12.load(context);
        textureLoader.l13.load(context);
        textureLoader.l14.load(context);
        textureLoader.l15.load(context);
        textureLoader.l16.load(context);
        textureLoader.l17.load(context);
        textureLoader.l18.load(context);
        textureLoader.l19.load(context);
        textureLoader.l20.load(context);
        textureLoader.l21.load(context);
        textureLoader.l22.load(context);
        textureLoader.l23.load(context);
        textureLoader.l24.load(context);
        textureLoader.l25.load(context);
        textureLoader.l26.load(context);
        textureLoader.l27.load(context);
        textureLoader.l28.load(context);
        textureLoader.l29.load(context);
        textureLoader.l30.load(context);
        textureLoader.l31.load(context);
        textureLoader.l32.load(context);
        textureLoader.l33.load(context);
        textureLoader.l34.load(context);
        textureLoader.l35.load(context);
        textureLoader.l36.load(context);
        textureLoader.l37.load(context);
        textureLoader.l38.load(context);
        textureLoader.l39.load(context);
        textureLoader.l40.load(context);
        textureLoader.l41.load(context);
        textureLoader.l42.load(context);
        textureLoader.l43.load(context);
        textureLoader.l44.load(context);
        textureLoader.l45.load(context);
        textureLoader.l46.load(context);
        textureLoader.l47.load(context);
        textureLoader.l48.load(context);
        textureLoader.l49.load(context);
        textureLoader.l50.load(context);
        textureLoader.l51.load(context);
        textureLoader.l52.load(context);
        textureLoader.l53.load(context);
        textureLoader.l54.load(context);
        textureLoader.l55.load(context);
        textureLoader.l56.load(context);
        textureLoader.l57.load(context);
        textureLoader.l58.load(context);
        textureLoader.l59.load(context);
        textureLoader.l60.load(context);
        textureLoader.l61.load(context);
        textureLoader.l62.load(context);
        textureLoader.l63.load(context);
        textureLoader.l64.load(context);
        textureLoader.l65.load(context);
        textureLoader.l66.load(context);
        textureLoader.l67.load(context);
        textureLoader.l68.load(context);
        textureLoader.l69.load(context);
        textureLoader.l70.load(context);
        textureLoader.l71.load(context);
        textureLoader.l72.load(context);
        textureLoader.l73.load(context);
        textureLoader.l74.load(context);
        textureLoader.l75.load(context);
        textureLoader.l76.load(context);
        textureLoader.l77.load(context);
        textureLoader.l78.load(context);
        textureLoader.l79.load(context);
        textureLoader.l80.load(context);
        textureLoader.l81.load(context);
        textureLoader.l82.load(context);
        textureLoader.l83.load(context);
        textureLoader.l84.load(context);
        textureLoader.l85.load(context);
        textureLoader.l86.load(context);
        textureLoader.l87.load(context);
        textureLoader.l88.load(context);
        textureLoader.l89.load(context);
        textureLoader.l90.load(context);
        textureLoader.l91.load(context);
        textureLoader.l92.load(context);
        textureLoader.l93.load(context);
        textureLoader.l94.load(context);
        textureLoader.l95.load(context);
        textureLoader.l96.load(context);
        textureLoader.l97.load(context);
        textureLoader.l98.load(context);
        textureLoader.l99.load(context);
        textureLoader.l100.load(context);
        textureLoader.locked.load(context);
        textureLoader.p1.load(context);
        textureLoader.p2.load(context);
        textureLoader.p3.load(context);
        textureLoader.p4.load(context);
        textureLoader.p5.load(context);
        textureLoader.p6.load(context);
        textureLoader.p7.load(context);
        textureLoader.p8.load(context);
        textureLoader.p9.load(context);
        textureLoader.p10.load(context);
    }
}
